apiVersion: my.api.group.rama.angi.platform/v1alpha1
kind: MyAppResource
metadata:
  labels:
    app.kubernetes.io/name: myappresource
    app.kubernetes.io/instance: myappresource-sample
    app.kubernetes.io/part-of: angiplatform
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: angiplatform
  name: myappresource-sample
spec:
  # TODO(user): Add fields here
  replicaCount: 2
  resources:
    memoryLimit: 60Mi
    cpuRequest: 100m
  image:
    repository: ghcr.io/stefanprodan/podinfo
    tag: latest
  ui:
    color: "34577c"
    message: "Hey there"
  redis:
    enabled: true
